services:
- type: web
  name: telegram-bot
  env: python
  plan: free
  buildCommand: "pip install -r requirements.txt"
  startCommand: "python main.py"
  envVars:
    - key: TELEGRAM_TOKEN
      sync: false
    - key: GROQ_API_KEY
      sync: false
    - key: WEBHOOK_URL
      sync: false
    - key: ADMIN_ID
      sync: false
